# Используем официальный образ Python
FROM python:3.9

# Установка зависимостей
RUN pip install aiogram==2.12.3

# Копируем файлы бота в контейнер
COPY admin_bot.py /app/
COPY database.py /app/

# Указываем рабочую директорию
WORKDIR /app

# Команда для запуска бота
CMD ["python", "admin_bot.py"]
